version: '3'
services:
  landing:
    build: .
    expose: [8080]
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`oyasumi.app`)
      - traefik.http.routers.landing.entrypoints=websecure